version: "2.4"
services:
  reverse_proxy:
    environment:
      - SERVER_NAME={{dns_name}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem
    volumes:
      - /opt/monitoring/data/nginx:/data
      - /opt/monitoring/data/ssl:/ssl:ro
      - /opt/monitoring/.overrides/reverse_proxy/includes:/etc/nginx/templates/includes/env
